### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by CalcProgrammer1** [gohai/vc4-buildbot#1]
I'm using your config file for v1 Pi and was getting vc4 drm errors about not being able to get the i2c dev node for the HDMI port.  If you compile in I2C driver for BCM2835 the DRM framebuffer works.  I have the 2708 and 2835 I2C drivers both enabled and built into the image.  Difference between my config and yours:

```
adam@Adam-Server:/media/RAID5/AndroidCode/kernel_raspberrypi_vc4$ diff config .config
1927c1927
< CONFIG_I2C_CHARDEV=m

---
> CONFIG_I2C_CHARDEV=y
1944c1944
< CONFIG_I2C_BCM2708=m

---
> CONFIG_I2C_BCM2708=y
1950c1950
< # CONFIG_I2C_BCM2835 is not set

---
> CONFIG_I2C_BCM2835=y
4428d4427
< 
```

**Comment by gohai** [comment]
@CalcProgrammer1 Thanks for pointing this out.. the current configs were a quick test to see if the upstream-based kernel works, but I didn't get around too debugging why it didn't.

**Comment by gohai** [comment]
Incorporated to default config, thanks.
