### ISSUE TITLE
Hi,   just wondering how link the BuildRaspbianVc4.py takes to run

### ISSUE THREAD

**Issue by Wiccy** [gohai/vc4-buildbot#11]
Hi there,  i started the script about 8 hours ago and it is still running,  any idea howlong it is supposed to take on a RaspberryPi 2?

**Comment by Wiccy** [comment]
sorry,  typo.  "link" in the title should read "long"

**Comment by gohai** [comment]
Are you running BuildRaspbianVc4.py directly from the shell? Then you should be seeing what it is doing - probably compiling the kernel (twice actually).. Should be done fairly soon though.
