### ISSUE TITLE
Official 7" touchscren support

### ISSUE THREAD

**Issue by AndreeeCZ** [gohai/vc4-buildbot#13]
Hello,

yesterday i built a full fresh raspbiain by gohai's buildbot.
There are still some glitches, but opengl speed improvement is really amazing.

My question is when do you plan supporting other outputs besides HDMI, as stated in a different issue:

> It's a known limitation that HDMI is the only output currently working.

In particular, when will we be able to use the official touchscreen (preferrably along with the touch drivers).
Or, is there some other method to get it to work?

Keep up the good work

**Comment by gohai** [comment]
Hi! My work really is just the script, the _real_ work is done by Eric Anholt with Broadcom. But this functionality missing is a known limitation currently, so there is no use contacting him about it. (He's looking into DSI.)

**Comment by AndreeeCZ** [comment]
I see, thank you for your response.

I was just curious on the very rough ETA for the touchscreen support.
