### ISSUE TITLE
VC4 Driver Status

### ISSUE THREAD

**Issue by bdbcat** [gohai/vc4-buildbot#5]
Thanks for this build bot.

I see that Eric made his latest commit for VC4 driver to the upstream tree in Mid July.  After watching his video presentation, it sure sounded like the work would be ongoing, with lots more to do.

Any insight on Eric's plans, or any other active effort on the VC4 driver?

Dave
Dev Lead,  OpenCPN

**Comment by gohai** [comment]
@bdbcat Which video presentation are you referring to? (The one that I've seen is already a bit more than a year old.)

I am not aware of Eric's or Broadcom's plans. He made some vc4 commits to [mesa](http://cgit.freedesktop.org/mesa/mesa/commit/?id=cfa980f49356eb2d94178f8cc9d67d01b4e3d695) only 10 days ago, and has been active working on the [upstream bcm2835](http://lists.infradead.org/pipermail/linux-rpi-kernel/2015-September/thread.html) kernel as well. But I agree, the pace of (visible) changes has slowed down a bit..

Best

**Comment by bdbcat** [comment]
http://www.element14.com/community/videos/16160/l/open-source-opengl-on-the-raspberry-pi

Looks like May, 2015, in Australia.

Interesting part about the hard-coded initial display configuration.
"Works for my monitor, probably not for yours..."

Just trying to decide if I (or Sean) should invest significant effort in this branch going forward.
We sure would like native hardware OpenGL support on RPI2 for OpenCPN.

Dave

**Comment by gohai** [comment]
January 2015. When using the vc4-kms-v3d-rpi2 kernel, the driver should work on every monitor that regular Raspbian (or rather: its firmware) supports. (This is the kernel that this script is currently making use of.)

I'd suggest you contact Eric directly, or the Raspberry Pi foundation.
