### ISSUE TITLE
fatal: unable to connect to anongit.freedesktop.org:

### ISSUE THREAD

**Issue by ghost** [gohai/vc4-buildbot#6]
Cloning into '/usr/local/src/gst-omx'...
fatal: unable to connect to anongit.freedesktop.org:
anongit.freedesktop.org: Name or service not known

Traceback (most recent call last):
  File "./BuildRaspbianVc4.py", line 647, in <module>
    buildGstreamer()
  File "./BuildRaspbianVc4.py", line 524, in buildGstreamer
    subprocess.check_call("git clone --recursive git://anongit.freedesktop.org/gstreamer/gst-omx /usr/local/src/gst-omx", shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git clone --recursive git://anongit.freedesktop.org/gstreamer/gst-omx /usr/local/src/gst-omx' returned non-zero exit status 128

**Comment by gohai** [comment]
Works here like a charm. Perhaps you had a connection outage or similar.

```
# git clone --recursive git://anongit.freedesktop.org/gstreamer/gst-omx
Cloning into 'gst-omx'...
remote: Counting objects: 4183, done.
remote: Compressing objects: 100% (2766/2766), done.
remote: Total 4183 (delta 3151), reused 1827 (delta 1407)
Receiving objects: 100% (4183/4183), 1.04 MiB | 498.00 KiB/s, done.
Resolving deltas: 100% (3151/3151), done.
Checking connectivity... done.
Submodule 'common' (git://anongit.freedesktop.org/gstreamer/common) registered for path 'common'
Cloning into 'common'...
remote: Counting objects: 3821, done.
remote: Compressing objects: 100% (2082/2082), done.
remote: Total 3821 (delta 2576), reused 2565 (delta 1729)
Receiving objects: 100% (3821/3821), 597.35 KiB | 326.00 KiB/s, done.
Resolving deltas: 100% (2576/2576), done.
Checking connectivity... done.
Submodule path 'common': checked out '9aed1d7a80a38b76f9441ecf181942df99f09c38'
```
