### ISSUE TITLE
Fatal Error Build

### ISSUE THREAD

**Issue by nighteagle1974** [gohai/vc4-buildbot#7]
Hi,

so i have an RPI 2 and new installed Jessie on an Class 10 16GB SD Card. I have only configure WLAN and Keyboard, Language, Timezone. Then i have expand Filesystem to use all the space of the SD-Card. Then i have start Buildbot and after 1h i have an Fatal Error.
It writes influence inconsistency ....

I can not copy it here, because i don't use SSH so i have to make an picture. For this i have start buildbot again and became cryptogenic signs after 1,5h.
Have someone build succesfull with the Buildbot and Jessie image?

Is there an ready to start image of rasbian jessie to test the VC4 driver?

Regards,

ng

**Comment by nighteagle1974** [comment]
I have used now this image:
http://sukzessiv.net/~gohai/vc4-buildbot/build/
It seems is an Jessie..

But now the same problem as the others have.. After Raspi-config reboot fails with black screen...

I will check is an display issue from the rpi2 and the config.txt.

**Comment by nighteagle1974** [comment]
So now i can use the image.
I have an IR-CAM for thermografic on the RPI and without the VC2 i have only 9 Frames in Fullscreeen.
So now i have 30 Frames. I start the cam-driver with only an X11 window without the full x11 Screen at bootup.

So all my experiments shown i need only an great hardware 2D acceleration for my IR-cam to show an correct and speedy video. Only Jessie+software acceleration is not to use.. with VC4 i think is oversized, because i don't need 3D accleration and often i see problems with the VC4 it hangs up the rpi and also the rpi feels a bit slowler on booting and also on input over keyboard. The Video-Out Composite is also not in function with VC4?

Somebody ideas what i can do only for hardware 2D acceleration on the RPI 2 ?
By the way..the CAM have only 382x288 px but is much for an IR CAM.

Regards
![rpi2_ir](https://cloud.githubusercontent.com/assets/1252182/11367841/ad2d1d00-92b6-11e5-9d3f-dc7c1ca26edf.jpg)

**Comment by nighteagle1974** [comment]
Hi,

so for the composite video-out i have only a "Rainbow-Bootscreen" and after few seconds RPI hangs.
Is there an solution to use the composite video out with the Jessie-VC4 Image?

Regards

**Comment by gohai** [comment]
@nighteagle1974 I don't think this is working/supposed to work yet. I've only got VC4 to work on HDMI screens so far (the Pi touchscreen doesn't work either). Please note that I am not the driver author, and that the Raspberry Pi foundation will sure release Raspbian with a VC4 driver when it's ready for public consumption.
